[tasks.clean]
command = "rm"
args = ["-f", "image.ppm"]

[tasks.run]
script = [
	"RUSTFLAGS=\"-C target-cpu=native\" cargo run --release > image.ppm"
]

[tasks.jpg]
script = [
	"ffmpeg -i image.ppm image.png",
	"mv image.* images"
]

[tasks.all]
dependencies = [
	"clean",
	"run",
	"jpg"
]